### ISSUE TITLE
[Question] How to disable encoding for segments with a forward slash

### ISSUE THREAD

**Issue by DoCode** [letsar/DoLess.UriTemplates#3]
How can I disable the encoding for path segments with a forwarding slash inside?

Template:
```
http://localhost/resource1{/resource2}{?q,pageindex,pagesize}
```
the data:
```
resource2 = "path/to/my/resource"
pagesize = 10
```
should result in
```
http://localhost/resource1/path/to/my/resource?pagesize=10
```

**Comment by letsar** [comment]
Hi @DoCode. For this You should use the `+` operator instead of the `/` one:
``` csharp
UriTemplate.For("http://localhost/resource1/{+resource2}{?q,pageindex,pagesize}")
           .WithParameter("resource2", "path/to/my/resource")
           .WithParameter("pagesize", 10)
           .ExpandToString();
```

**Comment by DoCode** [comment]
Thanks a lot! That's what I needed.
When the `resource2` is null, can a slash included inside the operator, like `{/+resource2}`

**Comment by letsar** [comment]
I'm not sure if the RFC6570 allows that, but maybe you can do something like that to handle null values:
``` csharp
UriTemplate.For("http://localhost/resource1{+resource2}{?q,pageindex,pagesize}")
           .WithParameter("resource2", variable?.EnsureRelativeUrl())
           .WithParameter("pagesize", 10)
           .ExpandToString();
```

where `EnsureRelativeUrl `is a method that prefixes this string with a `\` char if it does not start with it.
